#!/usr/bin/env python

"""
This is a small tool to convert Python enums into JavaScript enums.
Big thanks to Sajam!

Github: https://github.com/Sajam/pyjs_shared_enums

Edit:
I made some minor changes to adapt it to my version of Python.
"""

import os
import ast
import re
from optparse import OptionParser

import pen_n_paperless.common.keys as keys

BASE_PATH = os.path.normpath(os.path.dirname(__file__))
ENUM_CLASSES_NAMES = ('Generic', 'Statistics', 'Attributes', 'Armour', 'Weapons', 'History', 'Abilities', 'Tribes', 'Professions', 'Specializations', 'Traits', 'Avatars')
# ENUM_CLASSES_NAMES = ('Generic',)




class AstHelpers(object):

    supported_ast_types = (str, int, list)

    @staticmethod
    def ast_as_js(v):
        try:
            if type(v) == str:
                return '\"{}\"'.format(v)
            elif type(v) == int:
                return v
            elif type(v) == list:
                return '[{}]'.format(', '.join([str(AstHelpers.ast_as_js(el)) for el in v]))
        except Exception:
            return v

    @staticmethod
    def get_child_classes(node, class_name_or_names):
        # class_name_or_names = tuple(class_name_or_names)
        classes = []

        for n in ast.walk(node):
            if isinstance(n, ast.ClassDef):
                classes.append(n)

        return filter(lambda py_class: any([py_class.name in class_name_or_names]), classes)

    @staticmethod
    def get_assignments(node):
        assignments = []

        for n in node:
            if isinstance(n, ast.Assign):
                for t in n.targets:
                    # this part is a bit of a hack, could not find a way to access the value since I am using auto() to assign values to the enum members
                    assignments.append([t.id, keys.Key._generate_next_value_(t.id, 0, 0, [])])

        return dict(filter(lambda i: isinstance(i[1], AstHelpers.supported_ast_types), assignments))


class CommonEnumGenerator(object):

    # Must be a string that contain enum's source file path (relative_enum_file_path).
    AS_JS_ENUM_START = '// {python_relative_file_path}\n'

    # Must be an unique string that indicates end of single enum definition.
    AS_JS_ENUM_END = '// {}\n\n'.format('-' * 80)

    ENUM_AS_JS = '// autogenerated: DO NOT EDIT\n// lineno: {enum_lineno}\nconst {enum_name} = Object.freeze({{\n{enum_members}\n}});\n'
    ENUM_AS_JS = '{start}{enum}{end}'.format(start=AS_JS_ENUM_START, enum=ENUM_AS_JS, end=AS_JS_ENUM_END)


    def __init__(self, python_file_path, js_file_path):
        self.python_file_path = os.path.normpath(python_file_path)
        self.js_file_path = os.path.normpath(js_file_path)

        self.python_relative_file_path = self.python_file_path.replace(
            os.path.commonprefix([BASE_PATH, self.python_file_path]), '')
        
        self.output = ''
        # print('init complete')


    def __enter__(self):
        # open Python file and read contents
        self.python_file_handler = open(self.python_file_path, 'r')
        self.python_file_contents = self.python_file_handler.read()

        # remove output file if it exists
        if os.path.exists(self.js_file_path):
            os.remove(self.js_file_path)

        self.js_file_handler = open(self.js_file_path, 'w+')

        return self


    def generate(self):
        enums = self.get_enums_from_python_file()

        for enum in enums:
            self.output_add_enum(enum)

        self.js_file_handler.write(self.output)


    def get_enums_from_python_file(self):
        ast_tree = ast.parse(self.python_file_contents)
        return AstHelpers.get_child_classes(ast_tree, ENUM_CLASSES_NAMES)


    def output_add_enum(self, enum):
        members = AstHelpers.get_assignments(enum.body)
        members_as_js_strings_list = ['\t{}: {}'.format(k, AstHelpers.ast_as_js(v)) for k, v in members.items()]

        self.output += self.ENUM_AS_JS.format(
            python_relative_file_path=self.python_relative_file_path,
            enum_lineno=enum.lineno,
            enum_name=enum.name,
            enum_members=',\n'.join(members_as_js_strings_list)
        )

    def __exit__(self, type, value, traceback):
        self.python_file_handler.close()
        self.js_file_handler.close()


def main():
    parser = OptionParser(usage='Usage: %prog python_input_file_path [options]', version='%prog 1.0')
    parser.add_option('-o', '--output', dest='output', metavar='OUTPUT_FILE_PATH', help='Path to output JS file.')
    (options, args) = parser.parse_args()

    if len(args) < 1:
        parser.error('Missing argument.')
    elif not options.output:
        parser.error('No output file specified.')
    
    with CommonEnumGenerator(str(args[0]), options.output) as common_enum_generator:
        common_enum_generator.generate()


if __name__ == '__main__':
    main()
